ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS frontend_id BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS erp_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS market_id BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS market_customizer_id BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS level SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS parent_id BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount_profile TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS can_order BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS username TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS password TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS email TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS email_copy TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS country_code TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS language TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_language TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS webservice_key TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS company TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS tax_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS bank TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS bank_address TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS bank_branch TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS website TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS address_line1 TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS address_line2 TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS postal_code TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS city TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS phone TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS account_manager_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS account_manager_phone TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS account_manager_email TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS birth_date DATE,
  ADD COLUMN IF NOT EXISTS registered_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS favorites_notifications BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS key_code INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_confirmed BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS recovery_timestamp TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS receives_newsletters BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS standard_tier INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS owner_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stock_policy INT NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS location TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS street_type TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS neighborhood TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS state TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS state_registration TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS country TEXT,
  ADD COLUMN IF NOT EXISTS comment TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS registration_certificate TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS last_login_ip TEXT,
  ADD COLUMN IF NOT EXISTS last_login_country_code TEXT,
  ADD COLUMN IF NOT EXISTS blocked_by_suspicious_change BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS warehouse_code TEXT,
  ADD COLUMN IF NOT EXISTS old_erp_id TEXT,
  ADD COLUMN IF NOT EXISTS commercial_market_id BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS migrated BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS commercial_area_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS industrial_production INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS delivery_note TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS no_direct_approvals BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_cleaned BOOLEAN NOT NULL DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS customers_username_idx ON customers (frontend_id, username);
CREATE UNIQUE INDEX IF NOT EXISTS customers_email_idx ON customers (frontend_id, email);
CREATE INDEX IF NOT EXISTS customers_erp_id_idx ON customers (erp_id);
CREATE INDEX IF NOT EXISTS customers_name_idx ON customers (name);
CREATE INDEX IF NOT EXISTS customers_registered_at_idx ON customers (registered_at);
CREATE INDEX IF NOT EXISTS customers_is_active_idx ON customers (is_active);
CREATE INDEX IF NOT EXISTS customers_market_id_idx ON customers (market_id);
CREATE INDEX IF NOT EXISTS customers_level_idx ON customers (level);
CREATE INDEX IF NOT EXISTS customers_parent_id_idx ON customers (parent_id);
CREATE INDEX IF NOT EXISTS customers_discount_profile_idx ON customers (discount_profile);

CREATE TABLE IF NOT EXISTS customer_addresses (
  id BIGSERIAL PRIMARY KEY,
  customer_code BIGINT NOT NULL REFERENCES customers(code) ON DELETE CASCADE,
  erp_id TEXT NOT NULL DEFAULT '',
  address_code TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL DEFAULT '',
  company TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  postal_code TEXT NOT NULL DEFAULT '',
  city TEXT NOT NULL DEFAULT '',
  country_code TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  location TEXT NOT NULL DEFAULT '',
  street_type TEXT NOT NULL DEFAULT '',
  neighborhood TEXT NOT NULL DEFAULT '',
  state TEXT NOT NULL DEFAULT '',
  customer_erp_id TEXT,
  old_erp_id TEXT,
  migrated BOOLEAN NOT NULL DEFAULT false
);

CREATE UNIQUE INDEX IF NOT EXISTS customer_addresses_customer_erp_idx
  ON customer_addresses (customer_code, erp_id);
CREATE INDEX IF NOT EXISTS customer_addresses_country_code_idx
  ON customer_addresses (country_code);
