package domain

import "time"

type Customer struct {
	Code                      int64
	FrontendID                int64
	ErpID                     string
	MarketID                  int64
	MarketCustomizerID        int64
	Level                     int32
	ParentID                  int64
	DiscountProfile           string
	IsActive                  bool
	CanOrder                  bool
	Username                  string
	Password                  string
	Email                     string
	EmailCopy                 string
	CountryCode               string
	Language                  string
	ContactLanguage           string
	WebserviceKey             string
	Name                      string
	Company                   string
	TaxID                     string
	Bank                      string
	BankAddress               string
	BankBranch                string
	Website                   string
	AddressLine1              string
	AddressLine2              string
	PostalCode                string
	City                      string
	Phone                     string
	AccountManagerName        string
	AccountManagerPhone       string
	AccountManagerEmail       string
	BirthDate                 *time.Time
	RegisteredAt              *time.Time
	LastLoginAt               *time.Time
	FavoritesNotifications    bool
	KeyCode                   int32
	IsConfirmed               bool
	RecoveryTimestamp         *time.Time
	ReceivesNewsletters       bool
	StandardTier              int32
	OwnerID                   string
	StockPolicy               int32
	Location                  string
	StreetType                string
	Neighborhood              string
	State                     string
	StateRegistration         string
	Country                   string
	Comment                   string
	RegistrationCertificate   string
	LastLoginIP               string
	LastLoginCountryCode      string
	BlockedBySuspiciousChange bool
	WarehouseCode             string
	OldErpID                  string
	CommercialMarketID        int64
	Migrated                  bool
	CommercialAreaID          string
	IndustrialProduction      int32
	DeliveryNote              string
	NoDirectApprovals         bool
	IsCleaned                 bool
	Addresses                 []CustomerAddress
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}

type CustomerAddress struct {
	ID            int64
	CustomerCode  int64
	ErpID         string
	AddressCode   string
	Name          string
	Company       string
	Address       string
	PostalCode    string
	City          string
	CountryCode   string
	Phone         string
	Location      string
	StreetType    string
	Neighborhood  string
	State         string
	CustomerErpID string
	OldErpID      string
	Migrated      bool
}
